# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 18:32
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import sga.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('edx_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('due_date', models.DateTimeField()),
                ('grace_period', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('edx_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_students', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.Course')),
                ('grader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='sga.Grader')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('feedback', models.TextField(null=True)),
                ('grade', models.IntegerField(null=True)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('graded_at', models.DateTimeField(null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('student_document', models.FileField(null=True, upload_to=sga.constants.student_submission_file_path)),
                ('grader_document', models.FileField(null=True, upload_to='')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='sga.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='SGAUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graded_assignments', to='sga.SGAUser'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_assignments', to='sga.SGAUser'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.SGAUser'),
        ),
        migrations.AddField(
            model_name='grader',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sga.SGAUser'),
        ),
        migrations.AddField(
            model_name='course',
            name='administrators',
            field=models.ManyToManyField(related_name='administrated_courses', to='sga.SGAUser'),
        ),
        migrations.AddField(
            model_name='course',
            name='graders',
            field=models.ManyToManyField(related_name='graded_courses', through='sga.Grader', to='sga.SGAUser'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='sga.Student', to='sga.SGAUser'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sga.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('assignment', 'student')]),
        ),
    ]
