# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0002_auto_20160616_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grader',
            name='max_students',
            field=models.IntegerField(default=10),
        ),
    ]
