# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-30 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0002_student_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='consumer_key',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='edx_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='result_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
