# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import sga.backend.files
import sga.backend.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0003_auto_20160617_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AlterField(
            model_name='submission',
            name='grader_document',
            field=models.FileField(null=True, upload_to=sga.backend.files.grader_submission_file_path, validators=[sga.backend.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student_document',
            field=models.FileField(null=True, upload_to=sga.backend.files.student_submission_file_path, validators=[sga.backend.validators.validate_file_extension]),
        ),
    ]
