# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0004_auto_20160621_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='grace_period',
            field=models.IntegerField(default=0),
        ),
    ]
